# Generated by Django 4.0.4 on 2022-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
