# Generated by Django 4.0.4 on 2022-06-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='SubstenceAction',
        ),
        migrations.AddField(
            model_name='complaint',
            name='ProductCategoryRemark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='SustenanceAction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ActualDateForActionVerification',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Ageing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ComplaintClosureDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ComplaintRepeated',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ContainmentAction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='CustomerComplaint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='CustomerComplaintNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='CustomerLocation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='CustomerModel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='CustomerName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='CustomerPartNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='DefectDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='DocumentUploaded',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='EffectiveMontioringM1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='EffectiveMontioringM2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='EffectiveMontioringM3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='FourMCategory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='HDApplicablity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='HDModels',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ICAActualDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ICATargetDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='IssueReportedDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='IssueReportedMonth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='NewExisting',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OccurenceRootCause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OccurenceRootCauseActualDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OccurenceRootCauseResp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OccurenceRootCauseSideAction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OccurenceRootCauseTargetDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OutflowRootCause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OutflowRootCauseActualDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OutflowRootCauseResp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OutflowRootCauseSideAction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OutflowRootCauseTargetDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PPMNonPPM',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ProcessDesignSupplier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ProductCategory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='RejectedQuantity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ReportedArea',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='SourceOfComplaint',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='SystemAction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='TargetDateForActionVerification',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='UniqueComplaintNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='VarrocObservation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='VarrocPlant',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
