# Generated by Django 4.0.4 on 2022-06-01 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_alter_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 1, 12, 42, 40, 403324), null=True),
        ),
    ]
