# Generated by Django 4.0.4 on 2022-06-01 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_alter_complaint_partmanufacturingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 1, 12, 43, 20, 608158), max_length=200, null=True),
        ),
    ]
