# Generated by Django 4.0.4 on 2022-06-01 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_alter_complaint_partmanufacturingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='ActualDateForActionVerification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ComplaintClosureDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ICAActualDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ICATargetDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OccurenceRootCauseActualDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OccurenceRootCauseTargetDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 1, 12, 44, 24, 870794), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='TargetDateForActionVerification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
