# Generated by Django 4.0.4 on 2022-06-01 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_alter_complaint_actualdateforactionverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='OutflowRootCauseActualDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='OutflowRootCauseTargetDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 1, 12, 44, 48, 707187), max_length=200, null=True),
        ),
    ]
