# Generated by Django 4.0.4 on 2022-06-01 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_alter_complaint_outflowrootcauseactualdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 1, 18, 51, 3, 210424), max_length=200, null=True),
        ),
    ]
