# Generated by Django 4.0.4 on 2022-06-03 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_alter_complaint_partmanufacturingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ApproverRemarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 3, 11, 2, 11, 961895), max_length=200, null=True),
        ),
    ]
