# Generated by Django 4.0.4 on 2022-06-03 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_complaint_approverremarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 3, 11, 19, 41, 352408), max_length=200, null=True),
        ),
    ]
