# Generated by Django 4.0.4 on 2022-06-03 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_complaint_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='DefectDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PartManufacturingDate',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 3, 17, 10, 42, 987480), max_length=200, null=True),
        ),
    ]
